### ISSUE TITLE
Docker run command hanging 

### ISSUE THREAD

**Issue by lyonsrob** [foomo/pagespeed_exporter#10]
I want to start off by saying great app. I've got it running locally, but when I attempt my first scrape it appears the command is just hanging. After running `docker run -p "9271:9271".... I see only this message:

time="2018-12-21T03:52:28Z" level=info msg="starting pagespeed exporter version 75f1ad3 on address :9271 for 1 targets"

**Comment by smartinov** [comment]
Hi, sorry for not seing this message earlier!

So the docker command doesn't really hang, it just has a main process. If you want it to run in the background, run the docker command with -d!

e.g.  ``docker run -d -p "9271:9271" --rm foomo/pagespeed_exporter -api-key {KEY} -t https://google.com,https://prometheus.io``

But i'd suggest the docker-compose example!
