### ISSUE TITLE
Add campaign name and source for Analytics

### ISSUE THREAD

**Issue by momania** [foomo/pagespeed_exporter#13]
First of all, thanks for creating this!

Is it possible to implement the `utm_campaign` and `utm_source` parameters for Analytics, as described here:
https://developers.google.com/speed/docs/insights/v5/reference/pagespeedapi/runpagespeed ?

That way it is easier to separate the automated traffic from real traffic.

**Comment by smartinov** [comment]
No probs! I'd love to, think i might have some time today/tomorrow!

How'd you imagine it should be passed in?

**Comment by momania** [comment]
I guess either through a flag, like the rest, or an environment variable. Both work ok, but for sake of configuration consistency a flag would probably fit best.

**Comment by smartinov** [comment]
@momania it's implemented, you can check out https://github.com/foomo/pagespeed_exporter/blob/master/example/prometheus/config.yml how to configure it via JSON target.

You can now configure pagespeed via prometheus or command line (docker), and filter for campaign / source / locale / strategy

**Comment by momania** [comment]
Great, thanks! 👍

**Comment by n33pm** [comment]
Sry for reopen but i don't get it.

targets:
`{"url":"http://example.com","campaign":"pagespeed_exporter","source":"test"}`

But nothing happend in Analytics:
![image](https://user-images.githubusercontent.com/12273891/70867043-24f4a600-1f71-11ea-9c67-a7e50eaf23c3.png)
