### ISSUE TITLE
put lighthouse report on inhouse grafana

### ISSUE THREAD

**Issue by muzammil84** [foomo/pagespeed_exporter#15]
i want to put lighthouse report on our in-house centralized grafana, how do i do that.

i see below in docker-compose.yml but not sure what to change in it?

grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    volumes:
    - "grafana_data:/var/lib/grafana"
    - "./grafana/provisioning/:/etc/grafana/provisioning/"
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=s3cr3t

**Comment by muzammil84** [comment]
any help here?

**Comment by smartinov** [comment]
So, you might want to open up prometheus as a data source in your grafana and scrape it from there. I'm not sure about your in-house grafana set-up so I don't know how much could I help

**Comment by muzammil84** [comment]
this is sorted out. i ran this suite on central in-house grafana i got this dashboard along with many other project dashboards.
