### ISSUE TITLE
scrape hit duration not changing

### ISSUE THREAD

**Issue by muzammil84** [foomo/pagespeed_exporter#16]
i have changed scrape hit duration on config,yml but changes are not reflected on grafana. please see required pics below. i want to hit after 2 minutes basically. can anyone please help

![image](https://user-images.githubusercontent.com/28689934/56960818-af69d000-6b6f-11e9-98f2-31f1f8500ed1.png)

![image](https://user-images.githubusercontent.com/28689934/56961043-46368c80-6b70-11e9-98b0-572143eba2c0.png)

**Comment by smartinov** [comment]
@muzammil84 what does the log say for pagespeed_exporter?

**Comment by smartinov** [comment]
So, you'd have to set the source min-step to 120s and se tthe scrape interval to 120s
