### ISSUE TITLE
gettting error "error="googleapi: Error 429: Quota exceeded". Gave Google API key also

### ISSUE THREAD

**Issue by muzammil84** [foomo/pagespeed_exporter#17]
i gave 20 urls in docker-compose.yml file and google api key, getting below error in logs (docker logs example_pagespeed_exporter_1)

local:/home/muzammil.shaikh/pagespeed_exporter:  docker logs example_pagespeed_exporter_1
time="2019-05-02T08:23:17Z" level=info msg="starting pagespeed exporter version 75f1ad3 on address :9271 for 20 targets"
time="2019-05-02T08:24:23Z" level=warning msg="target scraping returned an error" error="googleapi: Error 429: Quota exceeded. Please wait a while and try again., rateLimitExceeded" strategy=desktop target="https://www......co.uk/mobile/phones/pay-monthly-contracts"
time="2019-05-02T08:24:23Z" level=warning msg="target scraping returned an error" error="googleapi: Error 429: Quota exceeded. Please wait a while and try again., rateLimitExceeded" strategy=mobile target="https://www......co.uk/mobile/coming-soon"
time="2019-05-02T08:24:23Z" level=warning msg="target scraping returned an error" error="googleapi: Error 429: Quota exceeded. Please wait a while and try again., rateLimitExceeded" strategy=mobile target="https://pat-www.......co.uk/mobile/best-sim-only-deals"

Google API key generated using --> https://developers.google.com/speed/docs/insights/v5/get-started

docker-compose.yml file below.

![image](https://user-images.githubusercontent.com/28689934/57064425-e5c85c00-6ce3-11e9-9b63-8139d0bf49d9.png)

**Comment by smartinov** [comment]
So, i'd presume you want to reduce the scrape times, try to configure prometheus to scrape less frequently, since the "free api key" does not allow so many requests

Once per 1-4 hours is more than enough, and will not break the quota!
