### ISSUE TITLE
Allow lighthouse categories exclusion (or inclusion)

### ISSUE THREAD

**Issue by astronaute77** [foomo/pagespeed_exporter#18]
Hi,

As per the PSI documentation, by default only "performance" lighthouse category is included in the report:
https://developers.google.com/speed/docs/insights/v5/reference/pagespeedapi/runpagespeed

It would be great if we could also have the same default behavior in the exporter, with the possibility to add other categories through configuration (or URL parameters).

**Comment by smartinov** [comment]
@astronaute77 so currently it includes all 5 as provided in the screenshot

https://github.com/foomo/pagespeed_exporter/raw/assets/dashboard.png?raw=true

Am I missing something? (except exclusion?)

**Comment by astronaute77** [comment]
> 
> 
> @astronaute77 so currently it includes all 5 as provided in the screenshot
> 
> https://github.com/foomo/pagespeed_exporter/raw/assets/dashboard.png?raw=true
> 
> Am I missing something? (except exclusion?)

Currently, everything is included by default. The idea is to have default google behavior as default (only performance) and be able to include the rest through configuration if needed.

Or, if you really want to have all included as default, we should have a way to exclude.

Also, PWA can often timeout.

**Comment by PhilippeR** [comment]
I fully aggree with  astronaute77 proposition.
