### ISSUE TITLE
It is possible to use it without docker

### ISSUE THREAD

**Issue by Mte90** [foomo/pagespeed_exporter#19]
Looking at the code require just the code to be compiled and the binary to be executed.

So it is possible to run it without docker? I am not sure because I didn't investigate in all the repo.

**Comment by janhalfar** [comment]
It is go, so compile it to a binary flavour you need and you are good to go ;)

**Comment by Mte90** [comment]
Cool, I wasn't sure because the readme don't mention that :-)
Thanks for the clarification!

**Comment by Mte90** [comment]
I am trying to get talking with Prometheus on the same machine where pagespeed exporter is running.
There is the config.yml but is not clear how to define the path of the pagespeed_exporter.
Also how to set the api key in this config.yml because as parameter is missing.

**Comment by Mte90** [comment]
Nevermind use http rest requests :-)
