### ISSUE TITLE
Add versioning on release page / docker images

### ISSUE THREAD

**Issue by thomaspeitz** [foomo/pagespeed_exporter#27]
Hey Stefan,

thanks for your project.

Any chance you could use some kind of versioning on your release page / docker images? - It frightens me to use "latest" and break something during restart of containers or during cluster upgrades of kubernetes.

Greetings, Thomas :)

**Comment by smartinov** [comment]
Hi @thomaspeitz , thanks for your kind words! That's a great suggestion, I'll try to update the versions accordingly so that we have a better release management.

**Comment by smartinov** [comment]
@thomaspeitz so, started adding tags, so I'll try to version it correctly!
