### ISSUE TITLE
Require Histogram metric types

### ISSUE THREAD

**Issue by Romiko** [foomo/pagespeed_exporter#37]
It makes sense that we store histogram metric types with predefined buckets for metrics regarding duration. 

e.g.
pagespeed_lighthouse_interactive_duration_seconds

However the only problem is due to the ephemereal nature of this, that would mean all counter based metrics would need to be PUSHED to a prometheus aggregator (not gateway) to keep the counts intact.

This allows for better measurements in prometheus using increase and rate functions.

See the "weaveworks/prom-aggregation-gateway".

So what we could do it offer both gauge and histogram versions of the metrics.. The user can then choose which to use.

Thoughts?

**Comment by smartinov** [comment]
@Romiko thanks for the interest! 

So, I'm wondering, what would you store from the gauge metric type to histogram? Score?

**Comment by smartinov** [comment]
Any news on this @Romiko ?
