### ISSUE TITLE
Cumulative Layout Shift = 0 for all sites

### ISSUE THREAD

**Issue by igorblizn** [foomo/pagespeed_exporter#38]
Cumulative Layout Shift is always = 0 pagespeed_lighthouse_cumulative_layout_shift_duration_seconds{host="https://www.google.com",path="/",strategy="mobile"} 0
For mobile and desktop, for any site. But score is valid.

As CLS is not 'time' parameter so it is 0 probably because of some pasring issue.
![2021-01-13 23_35_48-](https://user-images.githubusercontent.com/32087974/104513316-22db9b80-55f8-11eb-8d4a-4c65780c07dd.jpg)

**Comment by smartinov** [comment]
@igorblizn thanks for the input! I'll have a look!
