### ISSUE TITLE
Pass Google API Key during curl to /probe

### ISSUE THREAD

**Issue by RafaelSNascimento** [foomo/pagespeed_exporter#40]
Hello, i'm using the pushgateway method and i need to pass a googleAPIKey to prevent get this error
`Quota exceeded for quota metric 'Queries' and limit 'Queries per minute' of service 'pagespeedonline.googleapis.com'` when i hit `pagespeed-exporter:any_port/probe` with more than one target and running it in parallel.
There is a way to pass googleAPIKey in URL or Header?

**Comment by smartinov** [comment]
Hi @RafaelSNascimento 

Could you pass it via [example/docker-compose.yml](https://github.com/foomo/pagespeed_exporter/blob/master/example/docker-compose.yml#L14) the command line arguments in the docker-compose.yaml?

**Comment by RafaelSNascimento** [comment]
Yes @smartinov, but as I'm using the pushgateway method, I want to send the api-key in the url when hitting the /probe route, because there are several projects using 1 pagespeed_exporter instance. One api-key will no support all projects, i will create another pagespeed_exporter instance if is not possible.

**Comment by VladStepanov** [comment]
Hi! @RafaelSNascimento could you please share with the solution of the problem?
