### ISSUE TITLE
Issues with aarch64 & docker compose / kubernetes

### ISSUE THREAD

**Issue by initharrington** [foomo/pagespeed_exporter#41]
upx does not support aarch64 in alpine at this time - https://github.com/upx/upx/issues/441

Using an Apple M1, you cannot use this image to docker build (fails to find upx as it does not exist for that architecture) or deploy with docker-compose / k8s for docker (the container crashes on startup).

With docker-compose & k8s you will get the follow error:

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

I would suggestion something like docker buildx for github actions to build cross platform.
https://github.com/docker/setup-buildx-action

**Comment by smartinov** [comment]
@initharrington new version should fix this! Removed UPX since the gains weren't that big!

Check it out, and if everything works, feel free to close the ticket!

Thanks for pointing it out!

**Comment by initharrington** [comment]
@smartinov can you add the cross build in the github actions for qemu?
Thanks!

**Comment by smartinov** [comment]
Allright @initharrington, now arm is supported 

https://registry.hub.docker.com/r/foomo/pagespeed_exporter/tags
