### ISSUE TITLE
Could someone help setting this up, getting following error

### ISSUE THREAD

**Issue by john007abhilash** [foomo/pagespeed_exporter#48]
**Could not initialize pagespeed collectors** while accessing http://localhost:9271/probe?target=https://www.google.com

**Comment by smartinov** [comment]
Hi @john007abhilash is this still an issue?

**Comment by john007abhilash** [comment]
> Hi @john007abhilash is this still an issue?

No got it resolved, thanks.

**Comment by seriusokhatsky** [comment]
hi @john007abhilash
How did you solve it? I got the same error

**Comment by john007abhilash** [comment]
> hi @john007abhilash How did you solve it? I got the same error

You need to setup prometheus and grafana and configure the api key for google.

**Comment by seriusokhatsky** [comment]
OK, I will try. Docs says that API key is not always required.
