### ISSUE TITLE
google: could not find default credentials.

### ISSUE THREAD

**Issue by kim-ae** [foomo/pagespeed_exporter#59]
Hello,

I'm currently trying to execute a docker container locally just to get a feeling on how this would work, further I'll integrate on the k8s that I support.
Whenever I try to start the container I get his error: google: could not find default credentials, I understand that this is complaining that I don't have google credentials (probably for gcloud or something similar), but I just want to test it, and I'm able to execute the api commands that I got directly from the API Reference in the page speed site.
The command that I'm executing is:
```
docker run -p "9271:9271" --rm \
    --env PAGESPEED_TARGETS=https://google.com \  
    --env PAGESPEED_CATEGORIES=accessibility,pwa \
    foomo/pagespeed_exporter
```
How could I make the docker work? I did not see any additional configuration related with google credentials needed for this in the readme page.
Someone that has this knowledge could point me in the right direction?
Thanks in advance for the attention and assistance.

**Comment by vitebo** [comment]
I believe that passing a `PAGESPEED_API_KEY` environment is enough

**Comment by smartinov** [comment]
Hi there @kim-ae, you should be able to set PAGESPEED_API_KEY since that would indeed set the default key.

You have the docker-compose example that should work out of the box!
