### ISSUE TITLE
Support PageSpeed Insights API v4

### ISSUE THREAD

**Issue by Nyoroon** [foomo/pagespeed_exporter#6]
As v2 was deprecated and closed on Jun 2018.
Also new metrics available.
https://developers.google.com/speed/docs/insights/v4/reference/

**Comment by smartinov** [comment]
Thanks for the info! I'll see that i fix the exporter so that it works with the v4 reference!

Thanks @Nyoroon

**Comment by smartinov** [comment]
Latest version supports pagespeed v5 api!
