### ISSUE TITLE
New (docker) release

### ISSUE THREAD

**Issue by momania** [foomo/pagespeed_exporter#7]
I see you did quite some nice improvements lately. Any change you will do a new release soon, and also publish a new docker container?

**Comment by smartinov** [comment]
Yeah! So there is a lot of new stuff, which is not compatible with the old ones.
The new pagespeed is using lighthouse with real-user experience.

I've made an example (with docker and grafana) with custom dashboards

https://hub.docker.com/r/foomo/pagespeed_exporter/

Also, automatic releases are now enabled by default so newer releases will be available.

I'd suggest (if you want to check it out/ leave a suggestion)
1. Check out repository
2. Go to example
3. docker-compose up -d 
4. localhost:3000 (admin:s3cr3t)
5. Check out the metrics with metric comparisons (scores / load speed for real users / scores ... )

Any suggestions are welcome!

**Comment by momania** [comment]
Aaah, I completely missed this small name change
https://github.com/foomo/pagespeed_exporter/commit/f520ebd7f04122434b46e11e09f8dd65dffc2974

I'll give it a spin!

**Comment by momania** [comment]
Got it all running now.

Also found your Grafana sample dashboard in your repo. 
Imported it into my own instance, updated the datasource, and looks good!

👍

**Comment by smartinov** [comment]
Glad you like it!
