### ISSUE TITLE
helm chart or kubernetes manifests

### ISSUE THREAD

**Issue by cuotos** [foomo/pagespeed_exporter#8]
It would be great to be able to deploy to a k8s cluster.

A lot of people will already be using prom in k8s as its pretty easy to config, it should hopefully be able to start collecting metrics automatically once deployed.
As long as the dashboard files are easy to get at and install it has great potential.

**Comment by ervinb** [comment]
Hi @cuotos,

The Helm chart has been added, along with an example in the readme. Thanks!
